name: Build and Release

on:
  push:
    branches:
      - main
      - bubach/actions
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          # - macos-latest
          # - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 12
          cache: 'npm'
      - run: npm install --global --production windows-build-tools@4.0.0 --vs2019
      - run: npm config set msvs_version 2019
      - run: npm install --global cross-env
      - run: npm install
      - run: npm run release
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          draft: true
          prerelease: true
          files: |
            installer/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
