name: Build and Release

on:
  push:
    branches:
      - main
      - bubach/actions
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          # - macos-latest
          # - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 12
          cache: 'npm'
      - run: npm install --global --production windows-build-tools@4.0.0 --vs2019
      - run: npm config set msvs_version 2019
      - run: npm install --global cross-env
      - run: npm install
      - run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - id: package-json
      #   uses: actions/github-script@v4.0.2
      #   with:
      #     result-encoding: string
      #     script: |
      #       const package = require('./package.json');
      #       return package.version;
      # - uses: softprops/action-gh-release@v1
      #   with:
      #     draft: true
      #     prerelease: true
      #     name: assinador
      #     tag_name: 'v${{ steps.package-json.outputs.result}}'
      #     files: |
      #       installer/*
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
